<?php
// Nothing yet, just here so WP loads itd

require_once __DIR__ . '/includes/cpt-projects.php';
require_once get_template_directory() . '/includes/assets.php';

// add_action('after_setup_theme', function () {
// 	error_log("FNESL [functions.php] after_setup_theme – loading blocks…");
// 	require_once get_template_directory() . '/includes/blocks/hello-world/block.php';
// });

add_action('init', function () {
	foreach (glob(__DIR__ . '/includes/blocks/*/block.json') as $block_json) {
			$dir    = dirname($block_json);
			$name   = basename($dir);
			$handle = "fnesl-block-$name";

			// Load the asset file generated by Rollup
			$asset_file = "$dir/index.asset.php";
			$asset      = file_exists($asset_file)
					? include $asset_file
					: [ 'dependencies' => [], 'version' => filemtime("$dir/index.js") ];

			// Register script with deps + version
			wp_register_script(
					$handle,
					get_theme_file_uri("/includes/blocks/$name/index.js"),
					$asset['dependencies'],
					$asset['version'],
					true
			);

			// Register block.json with the script handle
			register_block_type($block_json, [
					'editor_script' => $handle,
			]);
	}
});

/**
 * Hooks into 'after_setup_theme' to enable theme features and register navigation menus.
 *
 * - Adds support for automatic document titles.
 * - Enables post thumbnails (featured images).
 * - Enables custom editor styles for the block editor.
 * - Enables default block styles for the block editor.
 * - Registers a 'primary' navigation menu.
 *
 * @see https://developer.wordpress.org/reference/functions/add_theme_support/
 * @see https://developer.wordpress.org/reference/functions/register_nav_menus/
 */
add_action('after_setup_theme', function () {
    add_theme_support('title-tag');
    add_theme_support('post-thumbnails');
    add_theme_support('editor-styles');
    add_theme_support('wp-block-styles');
		register_nav_menus([
			'primary' => __('Primary Menu', 'fnesl'),
	]);

});


/**
 * Hooks into 'enqueue_block_editor_assets' to add an inline script that locks post autosaving in the block editor.
 *
 * This prevents the editor from automatically saving posts by dispatching the 'lockPostAutosaving' action
 * via the 'core/editor' data store when the block editor assets are enqueued.
 *
 * @see https://developer.wordpress.org/reference/hooks/enqueue_block_editor_assets/
 * @see https://developer.wordpress.org/block-editor/reference-guides/data/data-core-editor/
 */
add_action( 'enqueue_block_editor_assets', function() {
    wp_add_inline_script(
        'wp-editor',
        'wp.data.dispatch("core/editor").lockPostAutosaving();'
    );
});
